### ISSUE TITLE
[Homework 2] Missing cases for HasDtype trait of Instruction

### ISSUE THREAD

**Issue by hestati63** [kaist-cp/cs420#104]
`Register` and `GlobalVariable` can be ptr of the `Load` since they treated as pointer.
However, `HasDtype` implementation of `Instruction` doesn't consider the case.

Below might be the fix:
```
diff --git a/src/ir/mod.rs b/src/ir/mod.rs
index d28975c..287fbd4 100644
--- a/src/ir/mod.rs
+++ b/src/ir/mod.rs
@@ -231,6 +231,17 @@ impl HasDtype for Instruction {
             Self::BinOp { dtype, .. } => dtype.clone(),
             Self::UnaryOp { dtype, .. } => dtype.clone(),
             Self::Store { .. } => Dtype::unit(),
+            Self::Load {
+                ptr:
+                    Operand::Register {
+                        rid: RegisterId::Local { .. },
+                        dtype,
+                        ..
+                    },
+            }
+            | Self::Load {
+                ptr: Operand::Constant(Constant::GlobalVariable { dtype, .. }),
+            } => dtype.deref().clone().set_const(false),
             Self::Load { ptr } => ptr
                 .dtype()
                 .get_pointer_inner()
```

Am I missing anything?

**Comment by cmpark0126** [comment]
Thank you for the suggestion! 

However, for me, the current version of code seems no problem. Because `Load` instruction only used when the operand represents the pointer value, and `GlobalVariable` can represent the pointer only. (please refer this code: [ir/mod.rs](https://github.com/kaist-cp/kecc-public/blob/3bef06455ea35c39555020fe44fdee496dba402d/src/ir/mod.rs#L755))

Could you tell me why you think like that more specifically? I think including example more helpful :)

**Comment by cmpark0126** [comment]
Thank you for the suggestion.

In this case, `ptr.dtype()` calls the function defined at [ir/mod.rs](https://github.com/kaist-cp/kecc-public/blob/f4dc5e426c200f6415858a113e2628ef0dd7ee95/src/ir/mod.rs#L378-L385), and I think you may have missed this implementation. Please check again :)

**Comment by hestati63** [comment]
I got it.
Thanks a lot:)
