### ISSUE TITLE
[HW2] about conditional expression

### ISSUE THREAD

**Issue by hestati63** [kaist-cp/cs420#119]
Hi, I have a question about conditional expression.

As I know, most of ir have the expression to represent the conditional expression.
For example, llvm uses `select` instruction for conditional expression.

Although it is possible to translate the conditional expression to ir by utilizing multiple blocks, it generates much complex output than using the designated instruction.

Is there any reason to choose this design?

**Comment by jeehoonkang** [comment]
In general, conditional expression cannot be translated to LLVM's `select` instruction.  For instance, let's consider the following conditional expression:

```c
f() ? g() : h()
```

The semantics of this expression is that (1) call `f()`, and (2) if it's true, call `g()`; otherwise, call `h()`.  In particular, only one of `g()` or `h()` is called.  This phenomenon is usually called "short-circuiting".

But LLVM's `select` instruction doesn't support short-circuiting.  Its operands are either constant or register, which is already fully evaluated beforehand.  To express short-circuiting, we need conditional branches.
