### ISSUE TITLE
[Homework 2] Allocation in conditional expression 

### ISSUE THREAD

**Issue by Pusnow** [kaist-cp/cs420#124]
In the video, when translating conditional expression, prof allocates a local variable to store result.

```rust
...

let val_then =
    self.translate_typecast(val_then, merged_dtype.clone(), &mut context_then)?;
let val_else =
    self.translate_typecast(val_else, merged_dtype.clone(), &mut context_else)?;

let var = self.alloc_tempid();
let ptr = self.translate_alloc(var, merged_dtype)?; // Allocation

let _ = context_then.insert_instruction(ir::Instruction::Store {
    ptr: ptr.clone(),
    value: val_then,
});
self.insert_block(
    context_then,
    ir::BlockExit::Jump {
        arg: ir::JumpArg::new(bid_end, Vec::new()),
    },
);

...
```
I think a register is enough for the purpose.
Is there any reason for this?
(clang also does not use local variable: https://godbolt.org/z/YkrBzs)

**Comment by jeehoonkang** [comment]
Yes, as LLVM shows, we can do it without introducing a local variable.  But I decided to introduce one in the model implementation of KECC because by doing so, we can avoid introducing phinodes in irgen.  In this design, the redundant local variable will be eliminated and phinodes will be introduced in mem2reg.

**Comment by Pusnow** [comment]
Thank you for the explanation.
