### ISSUE TITLE
[HW1] Problem with fuzzer

### ISSUE THREAD

**Issue by Gabriel4256** [kaist-cp/cs420#133]
Hi, I am having a problem with using fuzzer.
Error occurs even after pulling latest changes.

![image](https://user-images.githubusercontent.com/23405741/81983848-f5a4ab00-966e-11ea-90bb-1025ed2b7cb6.png)

I tested it on my ubuntu 18.04 server.
Please let me know if I am missing something.
Thank you.

**Comment by cmpark0126** [comment]
KECC returns exit code 101 when `panic!` occurs: https://rust-cli.github.io/book/in-depth/exit-code.html

Please try to execute `cargo run -- -p tests/test_polished.c` if you want to know why this message occurs.

After then, if you still don't know what happens here, please ask me again.

(FYI, when you attach the log, please use [Fenced code blocks](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks) not the picture)

**Comment by Gabriel4256** [comment]
Ok. I've found what's wrong. 
Thank you.

**Comment by zzanggu9399** [comment]
I had perfectly same issue with this issue after I moved my code environment from Linux server to Local Mac OS. Everything without this fuzz are same between online server and local ...

How can I fix it? I tried ```cargo run -- -p tests/test_polished.c ``` but I don't know why this error occurred. 

```thread 'main' panicked at 'assertion failed: struct_type.node.declarations.is_none()', src/c/parse.rs:325:33```

온라인 서버에서는 되는데 로컬에서는``` python3 tests/fuzz.py --print``` 가 위의 #133 과 똑같은 오류가 납니다... 제가 뭘 놓치고 있는걸까요?

p.s) I already finished HW1, but after I moved the code to local repository, I post this issue  because it bothers me. Is there any problem with the following assignments?
