### ISSUE TITLE
[HW2] Include multiple files for submission

### ISSUE THREAD

**Issue by christofides** [kaist-cp/cs420#200]
Hello!

In my solution for homework 2, I called the write_string() methods that were defined in homework 1. The calls are only for generating error messages so it is not important for the functionality but I have many calls to write_string() in my code.

However, it is only possible to submit one file for the grading at gg so my code crashes since it doesn'r recognize the write_string methods. Of course I could just remove all the calls for the sake of grading the code but since other people may also have split their codes into different files. I wonder if it is possible to allow us to send multiple files for the submission?

Best regards
Jesper Amilon

**Comment by pr0cf5** [comment]
I am having the same issue. I think we should be allowed to submit write_c.rs as well.

**Comment by cmpark0126** [comment]
I understand what the problem is, but it's hard to accept the suggestion.

First, implementing `write_c.rs` is for HW1. HW1 and HW2 need to be independent for grading.
Second, we expect that `write_string()` method does not critical effect on your `irgen/mod.rs` implementation. So, it may be easily deleted from your `irgen/mod.rs`.

Sorry for the inconvenience, and please resubmit `irgen/mod.rs` to gg.kaist.ac.kr after removing `write_string()` method from your original implementation.

**Comment by pr0cf5** [comment]
Thank you for the answer. But for tests like asmgen which has direct dependency for irgen, we will be allowed to upload two files, is that correct?

**Comment by cmpark0126** [comment]
When we test `asmgen`, we'll use ir examples in [`examples/asmgen`](https://github.com/kaist-cp/kecc-public/tree/master/examples/asmgen). So, it has no dependency on `irgen`.

**Comment by christofides** [comment]
Okey, thanks for reply!
