### ISSUE TITLE
[HW4] Question regarding where "to" and "not to" place phinodes?

### ISSUE THREAD

**Issue by Ngiong** [kaist-cp/cs420#206]
Hello,

I think I'm getting confused again regarding phinode placements in `DF(..) U DF(DF(..)) U ...`
In my previous question #166, it was mentioned that if the phinode is not used anywhere in the code, then we can skip adding phinode in those blocks.

My current implementation to handle this right now:
1. Place phinodes in all locations in `DF(..) U DF(DF(..)) U ...`. 
This mean, we're adding phinodes in all candidate locations, even though it's not necessary
2. Delete unnecessary phinodes that is not used anywhere (similar with deadcode)

This seems work, and I tested it pass almost all of the TCs, except:
1. the sample TC for mem2reg: `mem2reg.input.ir`, it is expected to have phinode in @sink's b0, while it's not used anywhere
```
fun unit @sink (i32) {

block b0:
  %b0:p0:i32
  ret unit:unit
}
```
2. `cond_and_loop.ir`, it is expected to have phinode in b17:p1 <t2> although it's not used anywhere
```
block b17:
  %b17:p0:i32:i
  %b17:p1:i32:t2
  %b17:i0:unit = nop
  j b8(%b17:p0:i32, %b14:p0:i32)
```

Do you think if I implemented mem2reg this way, can this work?
Or, can I get an explanation where to & where not to place phinode?

Thank you ^^

**Comment by jeehoonkang** [comment]
- For `mem2reg.input.ir`: the phinode is actually the function argument.  It's not used, but it should not be removed.

- For `cond_and_loop.ir`: it seems my algorithm decided to insert `%b17:p1:i32:t2` because the corresponding location `%l6` is loaded at `%b17:i0`.  The reason your algorithm decided to remove it is, actually, `%b17:i0` is not used at all.  So it seems your algorithm performs more deadcode-elimination-like optimizations than ours.

  I'm torn on this issue, because (1) your algorithm is also a valid mem2reg, but (2) it's difficult to write a good evaluator that'll say your algorithm is correct.  Before deciding on this matter, I'd like to ask if you could change your implementation in such a way that (1) it marks that `%b17:p1` is nominally used by `%b17:i0` so that (2) it doesn't remove out `%b17:p1`.

**Comment by Ngiong** [comment]
Well, if this works,
1. Ah, I see. I'm missing that this is a function argument. But since this is an IR, aren't we allowed to remove this since it's not used anywhere. I mean, can we optimize the function to behave as a non-parametric function? Since the fact that the parameter is not used anywhere in the code, it would yield the same result if we remove the parameter in our IR?

2. Okay, I'll try to patch my code first, and see if this can make me pass the TCs (and not breaking any other TC).

--
But I'm also curious, how do you determine if the phinode should/should not be inserted in the block?
