### ISSUE TITLE
[HW2] fuzzer error

### ISSUE THREAD

**Issue by rubidam** [kaist-cp/cs420#208]
안녕하세요 fuzzing 테스트중 에러가 발생하여 질문드립니다.
이슈 #93 에 올라온 1번과 5번에러가 계속해서 발생하는데 제가 이해한 것이 맞다면 이 부분은 테스트의 문제이고 이 부분을 해결한 것이 맞나요?
그리고 5번 에러에 대해 이슈 #193 에서 한번더 언급되었는데 여기서는 이 에러를 무시하고 다시 creduce를 하라고 하셨습니다. 그런데  reduce를 하는 과정이 짧게는 3분에서 길게는 10분까지 걸리며 이 두 에러만 빈번하게 발생하여 다른 에러를 거의 볼수가 없습니다. 하지만 코드를 제출하면 통과되지 않습니다.

이 이슈에 대한 해결책이 있나요?? 
아니면 계속해서 다른 에러가 발생할때까지 reduce를 해야 하나요?

1번 에러
```
void(a)() { 0 == a; }
int main() {}
```

5번 에러
```
int a;
int main() {
  int b;
  a = 8;
  for (; a > 0; a--) {
    b & 1;
    b = 0;
  }
}
```

++ 추가로 아래와 같이 새로운 에러가 발생하는데 첫번째 줄이 무엇을 의미하는지 잘 모르겠습니다.
이 코드에 대한 ir결과는 메인 함수에 대해서만 나오며 테스트를 하면 void로 선언하여 문제가 생깁니다.
```
# 1 "" 3
void main() {}
```

**Comment by cmpark0126** [comment]
Sorry for the inconvenience. The following answers will help.

First, please try to handle case1 in your solution. If the function has no return, please return default value. For example, `int main() {}` return 0, because default value of `int` is 0.

Second, we fixed the code to prevent the case2 in this commit: https://github.com/kaist-cp/kecc-public/commit/b79a713b5c2e02058d51a24d11813f4d19549508. Please try again.

FYI, `creduce`'s result is affected by `tests/reduce-criteria-template.sh`. If you face the problem again, please try to follow the direction of #170 also.

**Comment by rubidam** [comment]
답변 감사합니다.
그런데 1번에러의 경우 메인함수가 비어있는것은 적절하게 처리하였으나
```
void(a)() { 0 == a; }
```
이 부분에서 0과 a를 비교하는 부분이 문제가 생깁니다. 
```
error: 'i32' conflicts prototype's dtype, '[ret:unit params:()]*'
```
이와 같이 에러가 발생하는데 이 부분도 문제없이 작동하도록 저희가 처리해야하는 부분인가요?

**Comment by cmpark0126** [comment]
Please refer to this link: https://github.com/kaist-cp/cs420/issues/93#issuecomment-621562943

**Comment by rubidam** [comment]
답변감사합니다.
