### ISSUE TITLE
[Homework 7] Floating point calling convention.

### ISSUE THREAD

**Issue by Pusnow** [kaist-cp/cs420#209]
[GotBolt](https://godbolt.org/z/LtjN_S) maps floating point arguments to integer argument registers (a0-a7).

However, there are separate floating point registers (fa0-fa7).

[RISC-V ABI](https://riscv.org/wp-content/uploads/2015/01/riscv-calling.pdf) also uses them:

>If argument i < 8 is a floating-point type, it is passed in floating-point register fai; otherwise, it is passed in integer register ai. 

So, which one should we use?

**Comment by jeehoonkang** [comment]
(continuing the discussion of #211 2.)

> There are 2 ways to call a function: (1) allocating stack & (2) passing through a0, a1, a2, ... (if argument <= 8). And we know that if the function has Call Instruction, we must use the (1).
To satisfy hw7 (generate correct RISC-V code), is it possible to somehow "generalize" to only use only the (1)?

**Comment by cmpark0126** [comment]
Please refer to this link: https://godbolt.org/z/mkZvYQ

`Godbolt` provides two compilers that can be compiled into RISC-V: `RISC-V gcc 8.2.0` and `RISC-V rv64gc clang`.

At this time, as can be seen in the above example link, `RISC-V gcc 8.2.0` follows the calling convention of the RISC-V ABI, while `RISC-V rv64gc clang` not to follow.

So, please implement `asmgen` by referring to the behavior of `RISC-V gcc 8.2.0`.

FYI, for the final project, [`riscv64-linux-gnu-gcc-10`](https://github.com/kaist-cp/kecc#cross-compilation-and-architecture-emulation) will be used to link your code and test driver.
(`riscv64-linux-gnu-gcc-10` shows similar behavior to `RISC-V gcc 8.2.0`)

**Comment by jeehoonkang** [comment]
RISC-V has multiple calling conventions regarding floating-point numbers: https://github.com/riscv/riscv-elf-psabi-doc/blob/master/riscv-elf.md#-named-abis  Conventions differ on the use of floating-point registers.  In particular, the "LP64" ABI doesn't use `fa?` registers, while `LP64D` does.

It seems clang uses `LP64` by default, which I think is bug because `LP64D` is the default ABI for RV64GC (on which KECC is targeting).  If you add `-mabi=lp64d` to the compiler flag, then you'll get the expected result (i.e., using `fa?` registers for arguments and returns).


The specification for the assignments was confusing, so I'd like to declare:

- For homework 7, you don't need to observe the calling convention.  All test functions have the signature `() -> ()`, for which calling conventions don't matter at all.

- For project,you **need** to observe the `LP64D` calling convention.  Benchmark will ask whether you correctly implemented the calling convention.

**Comment by Pusnow** [comment]
Great! I will keep open this issue for other students.

**Comment by jeehoonkang** [comment]
I believe this issue is now sufficiently advertised :)  Thank you all for making such a wonderful discussion thread.

**Comment by kimjungwow** [comment]
Sorry for reopening issue, but I leave a comment because I'm confusing whether I can use `RISC-V rv64gc clang` for asmgen.

Professor said [`For homework 7, you don't need to observe the calling convention. All test functions have the signature () -> (), for which calling conventions don't matter at all.`](https://github.com/kaist-cp/cs420/issues/209#issuecomment-643937143), so I thought I can use `RISC-V rv64gc clang` for asmgen.

But I'm confusing now because TA had said [`So, please implement asmgen by referring to the behavior of RISC-V gcc 8.2.0.`](https://github.com/kaist-cp/cs420/issues/209#issuecomment-643796368).

I am sorry for asking same question after closing the issue, but can I use `RISC-V rv64gc clang` for HW7 asmgen?
