### ISSUE TITLE
[HW2] creduce makes an example that uses an uninitialized value in a condition

### ISSUE THREAD

**Issue by cyron1259** [kaist-cp/cs420#218]
Hi, #193 was resolved with the latest fix, but I am getting another erroneous example:
```
int a;
int main() {
  int b;
  for (; a < 6; a++)
    if (b)
      b = 0;
}
```
I tried multiple times but creduce keeps producing this one.

**Comment by jeehoonkang** [comment]
- It's definitely undefined behavior: an uninitialized variable (`b`) is read and branched upon.
- It's the bug of creduce.  It should not produce such output because it's undefined behavior.
- Sorry that we cannot help you much at this point of time.  We recommend you to investigate the big input before creduce.

**Comment by codingskynet** [comment]
Regarding this problem, on VS Code I can see the dynamic output of reduced code just opening `test_reduced.c` when running creduce. I can get buggy code by copying the semi-reduced code and try running it. This is some demanding, but I think you can find the buddy code not hard.
