### ISSUE TITLE
[HW 5] Question about solution implementation of gvn.

### ISSUE THREAD

**Issue by hestati63** [kaist-cp/cs420#219]
I'm looking up the "examples/ir3/complete_cond.ir", function `func_11`.

Below diagram displays the cfg of the func_11.
```
0 ─ 7 ───┐
└── 8 ── 9 ── 4 ─ 10───┐
         │    └── 11── 12───┐
         └─── 5 ─ 13───┐    │
              └── 14── 15 ── 6 ─ 1  ─ ...
                             └── 2  ─ ...
```

In this function, `cmp ne 0:i32 0:i32` is defined both in `b4` (`%b4:i0`) and `b5` (`%b5:i0`).
`b2` also defines the `cmp ne 0:i32 0:i32` (`%b2:i0`). As all incoming nodes have a definition of `cmp ne 0:i32 0:i32`, I think the definition should be merged through the phinode.
But the solution output (`ir4/complete_cond4.ir`) does not merge the definition.

Is there something missed?

**Comment by jeehoonkang** [comment]
@hestati63 thank you for asking an important question.

For the example mentioned above, we decided not to introduce a phinode at `b6` for being used at `b2` because the join point (i.e., `b6`) and the use point (i.e., `b2`) are different.  If the join point and the use point had been the same, then our algorithm would have introduced a phinode at the same block.

I admit that it's quite an arbitrary and ad-hoc choice of algorithm, but we need to somehow limit the scope of redundancy discovery and replacement.  we decided to limit the application of phinode instroduction to the case where the join point and the use point are the same largely because introducing a phinode far away from the use point, will likely affect register allocation negatively.

I'd like to leave the test cases as-is, because I believe this ad-hoc choice would not make it much more difficult to write a solution for this homework.  If so, please let me know.

**Comment by hestati63** [comment]
Thank you for your answer!
I have two questions about your points.

1. In my understanding, the reason that gvn introduces negative effect on the register allocation is they increase the live range of variables. But if it is the problem, what is the reason that you don't apply the "heuristic" on the value come from the dominator?

2. Does gvn always make register pressure? I think gvn might kill the variable at the early point of the program. If we don't introduce the gvn on a later definition, we might need to hold the input of the definition somewhere (register or memory).

**Comment by jeehoonkang** [comment]
- I don't understand the point 1...  혹시 한국어로 다시 질문해주실 수 있나요?  I'll translate it to English and then answer it.

- GVN may increase or decrease register pressure.  If two redundant registers are simultaneously existing, then GVN will remove one, thereby reducing register pressure.  If two redundant registers are far far away, then GVN will merge them, thereby enlarging its live scope and increasing register pressure.

  GVN anyway removes redundant computations in the hope that the later register allocation pass is clever enough to adequately deal with the enlarged live scope, e.g., by spliting it.  So that overall GVN is beneficial to the performance.

  (Not sure I'm answering your question; please asking again if it doesn't.  Thank you for asking good questions in series.)

**Comment by hestati63** [comment]
This is the Korean version of question 1: 
제 생각으로는 gvn에서 variable들의 live range가 증가하기 때문에 register pressure가 생기는 것 같니다. 하지만 이 문제는 phinode들로 introduce되는 값이 아니여도 발생하는 문제라고 생각되는데, phinode에 대해서만 말씀하신 heuristic을 적용하는 이유가 있나요?

**Comment by jeehoonkang** [comment]
@hestati63's question is that GVN generally increases register pressure, and why I'm specifically applying a heuristic to reduce register pressure due to introduced phinodes.

The answer is: because (1) in the case, a new phinode is inserted, while for all the other cases, registers are removed; and (2) the newly generated phinodes make the register allocation problem more complicated.  Furthermore, phinodes are generally more difficult to handle than normal registers in register allocation...

**Comment by hestati63** [comment]
Okay. I got the points.
Thanks a lot!
