### ISSUE TITLE
[HW2} Grader give different result with the one in KECC

### ISSUE THREAD

**Issue by umartaufiqul** [kaist-cp/cs420#242]
Hello.

When I submit the my result in to the submission grader for HW2_small, the grader gives out "failed" result. However, when I run it with "RUST_MIN_STACK=33554432 cargo test test_examples_irgen_small" command, it gives out "ok" result. I have pulled the newest version, and in case of inconsistency in my implementation, I have run the test for 10 times, and none of them give "failed" result. The result did give out "10 filtered out" info.

Is this due to the "filtered out" part? Or is it possible that there is a difference between the KECC test and the submission grader?

**Comment by christofides** [comment]
I also had issue with difference between gg grader and when running locally, #202. The problem for me was that I was running ubuntu 18 instead of ubuntu 20.

**Comment by umartaufiqul** [comment]
Ah but I used the provided server, and the Ubuntu version is already 20

**Comment by jeehoonkang** [comment]
@umartaufiqul Please send me an email that describes the situation in more detail: jeehoon.kang@kaist...

Your submission, check id, student id, and more information that may help me debugging this would be appreciated.

**Comment by umartaufiqul** [comment]
Email sent~

**Comment by cmpark0126** [comment]
It seems your code uses `LogicalAnd` as a binary operator of KECC IR. However, you must do not. 

Let me show a simple example: https://godbolt.org/z/zfw6_m

The code in link used `LogicalAnd` binary operator, but LLVM IR has no matching instruction for this operator. Because logical operators like `LogicalAnd` and `LogicalOr` must be translated using `block` and `branch` operator.

I believe [`examples/c/logical_op.c`](https://github.com/kaist-cp/kecc-public/blob/master/examples/c/logical_op.c) and [`examples/ir0/logical_op.ir`](https://github.com/kaist-cp/kecc-public/blob/master/examples/ir0/logical_op.ir) give you some idea to debug your code.

By the way, I don't know why your code passed the test in your local environment. Could you share the log messages of `RUST_MIN_STACK=33554432 cargo test test_examples_irgen_small`?
(please use [creating-and-highlighting-code-blocks](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks) when you share the log messages)

**Comment by umartaufiqul** [comment]
Ah, I see.

I actually didn't expect my code to pass, because before the June 12 update, it still failed here and there, so I was surprised that the test passed the small test.


Here is my log result of `RUST_MIN_STACK=33554432 cargo test test_examples_irgen_small`
```
Compiling kecc v0.1.0 (/home/s20170896/Works/kecc/kecc-public)
    Finished test [unoptimized + debuginfo] target(s) in 8.71s
     Running target/debug/deps/kecc-569514590f91d646

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/fuzz-b22fd85d07c8dde5

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/kecc-745b3e5d32df4a3c

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/test_examples-0f404fad24ae210a

running 1 test
test test_examples_irgen_small ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 10 filtered out
```

**Comment by cmpark0126** [comment]
@umartaufiqul 

Hmm... it's very strange... If you don't mind, could you share the results of `cargo run --bin fuzz examples/c/logical_op.c -i`?

**Comment by umartaufiqul** [comment]
This is the result for the command
```
Finished dev [unoptimized + debuginfo] target(s) in 0.30s
     Running `target/debug/fuzz examples/c/logical_op.c -i`
thread 'main' panicked at 'parse failed examples/c/logical_op.c', src/tests.rs:40:29
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by pr0cf5** [comment]
Does creduce affect the test pass/fail? If it is the case, I am very sorry for patching the creduce criteria...

**Comment by cmpark0126** [comment]
It's very strange... I don't know why parsing `examples/c/logical_op.c` failed.

Please check whether `examples/c/logical_op.c` has been modified from the original example code. 

If there is no change, please let me know again.

**Comment by umartaufiqul** [comment]
I have checked my `examples/c/logical_op.c` with the current example from KECC repository, and it is exactly the same

**Comment by umartaufiqul** [comment]
Ah. I found where the error seem. I think I confused my two different directories. Then I will close this issue. Thanks and sorry for the confusion

**Comment by jade227** [comment]
I'm suffering now with same problem.
I checked all of check list above this issue but I cannot find why gg grader for irgen small fails even if kecc grader success.
