### ISSUE TITLE
[HW7] kecc and qemu show different result for shift.c

### ISSUE THREAD

**Issue by hestati63** [kaist-cp/cs420#263]
For shift.c, the result of gcc and interp is different.

Below is log:
```sh
$ riscv64-linux-gnu-gcc -O1 ./examples/c/shift.c
$ strace qemu-riscv64-static -L /usr/riscv64-linux-gnu/ ./a.out 2>&1 | tail -n 2
exit_group(0)       
$ cargo run --release -- ./examples/ir0/shift.ir --irrun
[result] 1
```

**Comment by cmpark0126** [comment]
Actually, `gcc` returns the same result as `kecc`. So, please work based on the results of `gcc`. 

By the way, I don't know why `qemu` returns the different results. I will share the reason when I know it.

**Comment by hestati63** [comment]
Actually, doesn't grade metric compare the execution result of qemu-riscv64-static and kecc interp?

**Comment by hestati63** [comment]
`char a = 127; char b = a << 1` shows undefined behavior.

> If E1 has a signed type and nonnegative value, and E1 × 2^{E2} is representable in the result type, then that is the resulting value; otherwise, the behavior is undefined.

**Comment by cmpark0126** [comment]
Actually, it does not the problem of `qemu` but `riscv64-linux-gnu-gcc`. 
So, if you make appropriate assembly code, `qemu` will return the same result as `gcc`.

**Comment by hestati63** [comment]
Thanks!

**Comment by Medowhill** [comment]
**Section 6.2.5** of the C standard says that whether `char` is signed or not is implementation-dependent.

>  The implementation shall define `char` to have the same range, representation, and behavior as either `signed char` or `unsigned char`.

It seems that GCC for RISC-V treats `char` as `unsigned char`, while GCC for x86-64 treats `char` as `signed char`. For example, according to Godbolt,

```c
int main() {
    char a = 0xff;
    return a;
}
```

is compile to 

```asm
main:                                   # @main
        addi    a0, zero, 255
        ret
```

and

```asm
main:
        mov     eax, -1
        ret
```

respectively for RISC-V and x86-64. I believe that the issue can be resolved by using `signed char` instead of `char`. For example,

```c
int main() {
    char a = 127;
    signed char b = a << 1;
    unsigned char c = (unsigned char)b >> 1;

    return b == -2 && c == 0x7F;
}
```

rather than

```c
int main() {
    char a = 127;
    char b = a << 1;
    unsigned char c = (unsigned char)b >> 1;

    return b == -2 && c == 0x7F;
}
```

**Comment by LockOne** [comment]
It seems RISC-V gcc treats `char` as `signed char` ...

when you compile 
```
int main() {
    char a = 0xff;
    return a;
}
```
with -O0 option, you get 

```
main:
        ...
        li      a5,-1
        sb      a5,-17(s0)
        lb      a5,-17(s0)
        sext.w  a5,a5
        mv      a0,a5
        ...
```

**Comment by Medowhill** [comment]
When I compile

```c
int main() {
    char a = 0xff;
    return a;
}
```

with RISC-V gcc 8.2.0 on godbolt, the result is the following:

```asm
main:
        addi    sp,sp,-32
        sd      s0,24(sp)
        addi    s0,sp,32
        li      a5,-1
        sb      a5,-17(s0)
        lbu     a5,-17(s0)
        sext.w  a5,a5
        mv      a0,a5
        ld      s0,24(sp)
        addi    sp,sp,32
        jr      ra
```

It treats `char` as `unsigned char`. It may depend on versions...

Since the test case contains an implementation-dependent behavior, for me, it seems that it would be nice to fix the test case anyway whether gcc treats `char` as `unsigned char` or not.
