### ISSUE TITLE
[Homework 5] Special Case

### ISSUE THREAD

**Issue by HwangSeongha** [kaist-cp/cs420#273]
https://github.com/kaist-cp/cs420/issues/219#issue-638510745

위 링크에서 join point와 use point가 다르면 phinode를 만들지 않는다고 하였는데, 현재 block이 join point인지를 어떻게 알 수 있나요?
mem2reg에서 했던 것 처럼 반복해야하나요?

**Comment by jeehoonkang** [comment]
- @HwangSeongha's asking how to decide whether a block is join point or not (for homework 5).
- You'll calculate the leader value for the concerned expression, and if it's different for different incoming edges for a block, then the block is a join point.  (Not sure it explains clearly.  If not, please provide me with a more concrete example so that I can give you more concrete answers.)

**Comment by HwangSeongha** [comment]
감사합니다. 해결했습니다.
