### ISSUE TITLE
[HW7] Implementing type conversion between integers

### ISSUE THREAD

**Issue by pr0cf5** [kaist-cp/cs420#292]
I am trying to implement type conversion btwn integers by implementing the logic in `interp.rs`.

```rust
let result = if target_signed {
                    if width >= target_width {
                        // TODO: explain the logic in the future
                        let value = trim_unnecessary_bits(value, target_width as u128);
                        sign_extension(value, target_width as u128)
                    } else {
                        value
                    }
                } else {
                    trim_unnecessary_bits(value, target_width as u128)
                };
```

However, I don't understand the logic here. First, if the original width is larger than the target width, is there sign extension necessary? Second, if the original width is smaller than the target width, shouldn't the value should be sign extended?

**Comment by cmpark0126** [comment]
Actually, this logic is only for the KECC interpreter. 

First, `sign extension` is not necessary to assembly code, but KECC IR needed because all the value is stored in `u128`. 

Second, it's similar to the first case.

Therefore, it is recommended not to refer to this logic when implementing type conversion in HW7.
