### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by jeehoonkang** [kaist-cp/cs420#305]
Thank you for taking the compiler course.  I have to admit that this courses a little bit experimental in that it's my first time to teach compiler and the skeleton code is being concurrently built with the course itself.

I myself took a compiler course in 2012 when I was a senior undergraduate student.  I needed to build a C-to-ARM compiler in C++ from scratch.  I needed to debug a lot of segmentation faults at that time...  There was also a performance competition.  Overall it was one of the toughest courses I have ever taken (even tougher than graduate courses on algebras, compilers, operating systems, program analysis), but it was fun!  And I hoped maybe one day I can teach a similar course on compilers so that students can enjoy it.  I really hope you did.

Recognitions: @hestati63 and @Medowhill did a really good job of optimizing their compilers, with only about 40% overhead over `gcc -O`.  @Pusnow and @christofides also did a good job, with less than 200% overhead over `gcc -O`.  Congratulations!

**Comment by christofides** [comment]
Hello, thank you for giving the course, it was enjoyable although tedious at points :).
@Medowhill and @hestati63, I hope you do not mind if I ask you what optimizations you implemented (other than the ones in homework 3-6)? It would be interesting to hear what optimizations that give results.

**Comment by hestati63** [comment]
I implemented the following 6 optimizations other than the hw3-6:
- Peephole optimization.
- strength reduction
- strength reduction on loop
- loop invariant code motion
- deadcode elimination on phinode
- mem2reg on global variable

But the last optimization, mem2reg on global variable, shows a notable impact on the final result.
This might be the benchmark heavily load/store values on the memory rather than having costly computation over registers.
