### ISSUE TITLE
How did the realtime qna session went?

### ISSUE THREAD

**Issue by wenko99** [kaist-cp/cs420#31]
I wanted to participate in the Hangout meeting today at 10:30, but I failed to do so. 

I clicked "참여 요청" several times, but there was no relply.

So I am curious how the qna session went, to get ready for further qna sessions in this course. Was it a group meeting, or a 1:1 qna session? 

Also, I had no question, but I just wanted to listen what other students were asking. So, was it possible to stay in the meeting without any question during the realtime qna session?

Thanks in advance :)

+ I cannot figure out a way to add a label to this issue so I left it unlabelled.

**Comment by jeehoonkang** [comment]
- Oh, I'm sorry you didn't get invited.  I "admit"ted all invitation requests, but presumably Google didn't send your request to me :(
- It was a group meeting.  Students asked questions, and I answered.
- Next time, if you cannot get in the Q&A session, please leave an issue here ASAP so that I can handle immediately.  Sorry for your inconvenience today.

**Comment by wenko99** [comment]
Thank you, professor.

Hope I can participate next time! :)
