### ISSUE TITLE
[Question] Formatting force policy in grade-hw1.sh

### ISSUE THREAD

**Issue by hyn2028** [kaist-cp/cs420#339]
Hello.

If I look at the contents of grade-hw1.sh, formatter, linter, and test are performed sequentially.

At this time, if there is any unsatisfactory item, the shell script does not proceed there and is aborted.

So, in order to get all the points, do I have to understand that there should be no problem with the 'coding style' from the formatter's point of view?

Thank you.

**Comment by minseongg** [comment]
The purpose of using formatter and linter is not to waste your precious time on such little things like formatting, improving readability, and enhancing safety. ([#155](https://github.com/kaist-cp/cs420/issues/155))

Since they will automatically format your source code and suggest code changes, you can use it without understanding. However, if you understand the meaning of each formatting and suggestion, you will be able to write the Rust code in an ergonomic way.

FYI: You can automatically format your source code by using `cargo fmt --all`.

**Comment by hyn2028** [comment]
After applying the suggestions of the formatter and linter, I will run the self-grader.

Thank you.
