### ISSUE TITLE
[Homework 2] IRgen (due: 8th of July)

### ISSUE THREAD

**Issue by jeehoonkang** [kaist-cp/cs420#35]
- Refer to the skeleton code: https://github.com/kaist-cp/kecc-public  Please be noted that **the skeleton code will likely change quite frequently.**  Please merge the upstream changes to your development.

- For homework 2, implement the IR generator: https://github.com/kaist-cp/kecc-public/blob/master/src/irgen/mod.rs#L24  Given a C AST, you should generate an equivalent IR.

- The forthcoming lecture videos will explain how to do this work.

- While it is due on 8th of July, I strongly recommend you to start as early as possible.  We will enjoy other pieces of homework at the later stage of the semester.

- The grading scheme is simple: you either implement a complete IRgen or not.  You can submit your code multiple times.  You can grade your submission yourself by running, e.g., `cargo test --release test_examples_irgen` and `python3 tests/fuzz.py -i -n30`.

- If fuzzer finds a buggy input for your IRgen, you can reduce it as follows: `python3 tests/fuzz.py -i --reduce; cat tests/test_reduced.c`.  We strongly recommend you to do this homework in a TDD way: fuzz, reduce, debug, repeat.

- Submit your `irgen/mod.rs` to https://gg.kaist.ac.kr/assignment/8/ (big) and https://gg.kaist.ac.kr/assignment/9 (small).

**Comment by jeehoonkang** [comment]
You may need to increase the call stack size for this homework: https://github.com/kaist-cp/kecc-public#test  The grading system will use 8MiB of call stack.

**Comment by cmpark0126** [comment]
**IMPORTANT**: the skeleton code is updated

- Please download the upstream changes: https://github.com/kaist-cp/kecc-public/commit/3bef06455ea35c39555020fe44fdee496dba402d
  - Now Fuzzer will show information on how many tests it skips. (#71)
  - Now compile error does not occur if you merge the upstream code into your code. By the way, if you already implemented A, conflict may occur. So, after merging the upstream code, please check if the compilation is possible and resolve the conflict problem. (#90)
  - Existing 'Dtype::is_const()' was modified to check only 'is_const' field of `Dtype` itself, and a function 'Dtype::is_immersible()' was newly created to check if 'Dtype' was immutable. Please check [`dtype.rs`](https://github.com/kaist-cp/kecc-public/blob/3bef06455ea35c39555020fe44fdee496dba402d/src/ir/dtype.rs#L724-L776) carefully. (#98)
  - Now you can test binary operator expression using the floating-point variable. Please check [interp.rs](https://github.com/kaist-cp/kecc-public/blob/3bef06455ea35c39555020fe44fdee496dba402d/src/ir/interp.rs#L551-L605)
    - We added example code also. [float.c](https://github.com/kaist-cp/kecc-public/blob/master/examples/c/float.c), [float2.c](https://github.com/kaist-cp/kecc-public/blob/master/examples/c/float2.c)

Minor updates may continue to be made, but they will not interfere with the progress of the homework1 and homework2. Sorry for the inconvenience caused by the late update & Thank you for waiting.

**Comment by cmpark0126** [comment]
Skeleton code is updated:
- Please download the upstream changes: https://github.com/kaist-cp/kecc-public/commit/e81247ba542bf30f0fb4d87a069085d772d6378a
  - Fix `Dtype::is_scalar` method. (https://github.com/kaist-cp/cs420/issues/114)
  - Fix pointer comparison logic in KECC interpreter. (https://github.com/kaist-cp/cs420/issues/127)
  - Add `irrun` option to run arbitrary C or IR code using the KECC interpreter. (https://github.com/kaist-cp/cs420/issues/136)
  - Add KECC IR examples of C files in the `examples/c` to `examples/ir`. (https://github.com/kaist-cp/cs420/issues/130)

FYI, I expect this update doesn't affect the grading.

**Comment by jeehoonkang** [comment]
The ["big" grader](https://gg.kaist.ac.kr/assignment/8/) and the ["small" grader](https://gg.kaist.ac.kr/assignment/9/) are now open.  Please submit your solution to gg.

**Comment by cmpark0126** [comment]
**IMPORTANT**: If you use the functions from `write_c.rs` when implementing HW2, please delete these functions from your original solution before submitting it to gg.

Please refer to the following link for a discussion of this policy: #200

**Comment by cmpark0126** [comment]
**IMPORTANT**

`examples/c/float2.c` has fixed in [the latest update](https://github.com/kaist-cp/kecc-public/commit/6146714112e76e372afb45b354deca6088888fbb), because it showed undefined behavior before.
So, please resubmit your solution to gg. (I expect your solution works well with the new example if it passed the test before)

Sorry for the inconvenience.

**Comment by cmpark0126** [comment]
**IMPORTANT**: We just nullified the existing submissions of homework 2 to gg.kaist.ac.kr due to #270.

Please resubmit your solution. Sorry for the inconvenience.
