### ISSUE TITLE
[Question, HW2] How can I calculate size of array with pointer?

### ISSUE THREAD

**Issue by gmlwns2000** [kaist-cp/cs420#353]
In `translate_expr_rvalue`, the array pointer is automatically converted into an element pointer. However, in `SizeOfVal` of `translate_expr_rvalue`, I couldn't calculate the size of the array because the retrieved type is not an array.

if given `sizeof(A)` then, 
```rust
SizeOfVal => {
  operand = translate_expr_rvalue(A)
  return operand.dtype().sizeof()
}
```

But operand is a pointer to the element. If A is `int[10]`, then the operand will be `int*`. Therefore, always operand size is `8`. How can I fix this problem? At the first time, I thought I could just skip `convert_array_to_pointer`. But it would be inefficient because the array is a pointer and there is many pointer operations to the array in a typical workload. So if I keep the array type on the array pointer, then I have to convert the array pointer when I use pointer operation.

**Comment by minseongg** [comment]
For `sizeof` operator with `expression`, you need to implement a logic that returns the type of the expression without (1) Lvalue-to-rvalue, (2) array-to-pointer, (3) function-to-pointer conversions. ([Reference](https://en.cppreference.com/w/cpp/language/sizeof))

There are some hints for implementing that logic.

- To calculate the size of array, as you mentioned, you could just skip `convert_array_to_pointer`.
- You can only consider expressions supported by the KECC. ([src/c/parse.rs#L458-L481](https://github.com/kaist-cp/kecc/blob/main/src/c/parse.rs#L458-L481))
- Since `sizeof` does **not evaluate the expression**, you do not need to translate the expression into IR.

**Comment by gmlwns2000** [comment]
Hi @minseongg,

Thank you for your help! I solve the problem by just skipping `convert_array_to_pointer` :)

**Comment by minseongg** [comment]
Yes, `sizeof` does not evaluate the expression.

You can see the details in https://en.cppreference.com/w/cpp/language/expressions#Unevaluated_expressions.

For example, the return value of the following C program is 3.

```c
int main() {
    int x = 3;
    int y = sizeof(++x);
    return x;
}
```

**Comment by gmlwns2000** [comment]
@minseongg Thank you for the good references.
I fixed my compiler! :)

**Comment by minseongg** [comment]
Added `sizeof3.c` test case. (https://github.com/kaist-cp/kecc-public/commit/44d898f568fe4cbfa863e5e35dc54baaf6d2b7f7)

**Comment by Lee-Janggun** [comment]
Hello, I noticed that the link in https://github.com/kaist-cp/cs420/issues/353#issuecomment-1077007307 is to the private repo. For anyone wondering, the proper link is https://github.com/kaist-cp/kecc-public/blob/main/src/c/parse.rs#L458-L481

**Comment by minseongg** [comment]
@Lee-Janggun Thanks! we fixed it.
