### ISSUE TITLE
[HW2] Do I have to handle invalid syntax?

### ISSUE THREAD

**Issue by ShinWonho** [kaist-cp/cs420#383]
Hello,

I'm wondering if I have to consider invalid syntax.

For example, in additive operators (6.5.6), there is some constraints about it.

```
For addition, either both operands shall have arithmetic type, or one operand shall be a
pointer to a complete object type and the other shall have integer type.
```

According to the spec, `(pointer) + (pointer)` is invalid syntax.

Here is my questions.
1. Does parser catch the invalid syntax?
2. Are there any test cases containing invalid syntax?
3. If so, do I have to throw IrgenError in the invalid syntax?

**Comment by minseongg** [comment]
In [Compiler organization](https://docs.google.com/presentation/d/1SqtU-Cn60Sd1jkbO0OSsRYKPMIkul0eZoYG9KpMugFE/edit#slide=id.g7a6ebdd23e_0_65), there are two separated components, Parser and Type checker. In parser, it constructs AST from the input code based on the syntax of the language specification. And in type checker, it checks the validity of the constructed AST based on the type checking for the nodes of the AST.

For the constraints in your question, it requires type checking to catch it because we need to know the type of each operand in the additive expression. Since this is done in the type checker, parser cannot catch the error. For example, `lang-c` parser can constructs AST from the below C program even if it violates the constraints and cannot be compiled.

```c
int main() {
    int *a, *b;
    int *c = a + b;
}
```

> Does parser catch the invalid syntax?

Yes.

However, parser cannot catch the error from the constraints in your question because actually it is not the invalid syntax. (See the above explanation) But we do not include test cases which violates any constraints in C specification because we only consider test cases which can be compiled by clang.

> Are there any test cases containing invalid syntax?

No. We only consider test cases which can be compiled by clang.

**Comment by ShinWonho** [comment]
Thank you for the answer!
Now I understand it.
