### ISSUE TITLE
[HW2] What is the result type of comparison operation?

### ISSUE THREAD

**Issue by ShinWonho** [kaist-cp/cs420#384]
Hello,

I'm confused with the result type of comparison operation.

According to the relational operators(6.5.8) and equality operators(6.5.9), result type is `int`

```
Each of the operators < (less than), > (greater than), <= (less than or equal to), and >=
(greater than or equal to) shall yield 1 if the specified relation is true and 0 if it is
false. The result has type int.

...

The == (equal to) and != (not equal to) operators are analogous to the relational
operators except for their lower precedence. Each of the operators yields 1 if the
specified relation is true and 0 if it is false. The result has type int. For any pair of
operands, exactly one of the relations is true.
```

However, result type is `u1` in KECC ir.

```
%b6:i2:u1 = cmp eq %b6:i1:i32 9:i32
```

So, I think there is conflict b/w the spec and KECC ir.

Is there any thing I misunderstand?

What is the correct result type of comparison operation?

**Comment by minseongg** [comment]
In our IR, we defined return type of the `cmp` operation as `u1` because it can represent the whole range of the result of `cmp` operation. (0 or 1) This is not the same as C specification, but it is enough to guarantee that your generated IR behaviors same as C input program.

Let's think for the example you provided.

[simple_cond.c](https://github.com/kaist-cp/kecc-public/blob/main/examples/c/simple_cond.c):

```c
int f(int x) {
    return x + 8;
}

int main() {
    int x = 0;
    int y = (x++ == 1) ? 1 : 2;

    return f((x < y) ? x : 2) == 9;
}
```

For the `f(..) == 9` expression in line 9, we inserted `typecast` instruction after `cmp` instruction to typecast the result of the comparison operator to `i32` and its behavior is same as the C input program.

[Translation of `f(..) == 9` in line 9](https://github.com/kaist-cp/kecc-public/blob/main/examples/ir0/simple_cond.ir#L64-L66):

```
...
%b6:i2:u1 = cmp eq %b6:i1:i32 9:i32
%b6:i3:i32 = typecast %b6:i2:u1 to i32 << Typecasting to `i32`
ret %b6:i3:i32
```

However, for the `x++ == 1` expression in line 7 and `x < y` expression in line 9, the result of the expression is used as condition of the conditional expression. In the C specification 6.5.15, it says

> The first operand is evaluated; there is a sequence point after its evaluation. The second operand is evaluated only if the first compares unequal to 0; the third operand is evaluated only if the first compares equal to 0.

According to this, we only need to know the return value of the condition is zero or non-zero. To know this, it is enough to check the return value in `u1` type and its behavior is same as C input program without additional typecast to `i32`.

[Translation of `x++ == 1` in line 7](https://github.com/kaist-cp/kecc-public/blob/main/examples/ir0/simple_cond.ir#L33-L34):

```
...
%b0:i4:u1 = cmp eq %b0:i1:i32 1:i32
br %b0:i4:u1, b1(), b2()
```

[Translation of `x < y` in line 9](https://github.com/kaist-cp/kecc-public/blob/main/examples/ir0/simple_cond.ir#L49-L50):

```
...
%b3:i4:u1 = cmp lt %b3:i2:i32 %b3:i3:i32
br %b3:i4:u1, b4(), b5()
```

**Comment by ShinWonho** [comment]
So, some features in KECC ir do not follow the C specification (with some reason), right?
Now, I understand it.
Thank you for the answer!
