### ISSUE TITLE
[HW6] Algorithms that depend on stages that are performed repeatedly

### ISSUE THREAD

**Issue by hyn2028** [kaist-cp/cs420#397]
I'm currently implementing deadcode elimination.

Does the compiler toolchain run one stage (e.g. deadcode) until there is no change?
So, can it be assumed that the stage will be called more than once unconditionally (at least 2 times)?

That is, by taking advantage of this property, when I design a stage, do I not have to finish the optimization in one stage?

**Comment by minseongg** [comment]
For the deadcode elimination stage, `DeadcodeInner::optimize` is called repeatedly until it returns `false` (This is because `Deadcode` is defined as `FunctionPass<Repeat<DeadcodeInner>>`.). Therefore, the optimize function is called more than once except it returns `false` at the first call.

You may design the stage with the assumption that optimization is finished in multiple calls.

**Comment by hyn2028** [comment]
Thank you. This makes the design much simpler.
