### ISSUE TITLE
[Question] [HW2] Should the IR result always the same with solution?

### ISSUE THREAD

**Issue by junsooo** [kaist-cp/cs420#400]
Hello. Now i'm doing HW2.

On simple_for.c, the result of my IR is this:

```
fun i32 @main () {
init:
  bid: b0
  allocations:
    %l0:i32:i
    %l1:i32:sum

block b0:
  %b0:i0:unit = store 0:i32 %l1:i32*
  j b1()

block b1:
  %b1:i0:i32 = load %l0:i32*
  %b1:i1:unit = store 0:i32 %b1:i0:i32
  j b2()

...
```

And the ir0's solution is this:

```
fun i32 @main () {
init:
  bid: b0
  allocations: 
    %l0:i32:i
    %l1:i32:sum

block b0:
  %b0:i0:unit = store 0:i32 %l1:i32*
  j b1()

block b1:
  %b1:i0:unit = store 0:i32 %l0:i32*
  j b2()

...
```

So i have different block b1 with solution.
But i think anyway the result is same, because %b1:i0:i32 == load %l0:i32*. So i think my solution is correct. Is there any something i missing? (Maybe it is different because the solution is `%b1:i0:unit = store 0:i32 %l0:i32*`, not `%b1:i0:unit = store 0:i32 load %l0:i32*`.)

By the way, I'm really curious about my IR because my code is almost same with skeleton code(which provided in video), and why the inconsistency happens with ir solution. Do you have any idea for this problem? Thank you.

**Comment by Lee-Janggun** [comment]
As long as the grading script works, it should be fine. For why you have an extra load, a possibility is that you are treating expressions when they are rvalue and lvalue are the same. When they are rvalue, we need to load from them. When they are lvalue, we don't need to.

**Comment by minseongg** [comment]
You can see the result of IR interpreter by using `cargo run --features=build-bin -- --irrun <IR FILE PATH>`. For your IR, it gives an invalid memory accessing error.

The difference between your IR and reference IR is that your IR gives the value of `i` as destination operand of `store` instruction, and reference IR gives the address of `i` (= `&i`) as destination operand of `store` instruction.

Since `store` instruction is storing value to the memory, you need to give a pointer-typed value that represents the address of memory as destination operand.

Your IR:

```
fun i32 @main () {
init:
  bid: b0
  allocations:
    %l0:i32:i
    %l1:i32:sum

block b0:
  %b0:i0:unit = store 0:i32 %l1:i32*
  j b1()

block b1:
  %b1:i0:i32 = load %l0:i32* // the value of `%b1:i0:i32` is `i`
  %b1:i1:unit = store 0:i32 %b1:i0:i32 // store 0 to the memory at `i`, which occurs error
  j b2()

...
```

In ir0's solution:

```
fun i32 @main () {
init:
  bid: b0
  allocations: 
    %l0:i32:i
    %l1:i32:sum

block b0:
  %b0:i0:unit = store 0:i32 %l1:i32*
  j b1()

block b1:
  %b1:i0:unit = store 0:i32 %l0:i32* // store 0 to the memory at `&i`, no error
  j b2()

...
```

As @Lee-Janggun said, I recommend you to check you're treating lvalue expression well. The translation of lvalue expression should have pointer type.

**Comment by junsooo** [comment]
@Lee-Janggun @minseongg  Thank you very much. Your explanation was really helpful.
