### ISSUE TITLE
[Question] [HW2] Having trouble with pointer.c UnaryOperator::Address, Indirection

### ISSUE THREAD

**Issue by junsooo** [kaist-cp/cs420#404]
Hello. I'm doing HW2, and i'm having hard time with pointer.c(UnaryOperator::Address, UnaryOperator::Indirection)

My smaller version of pointer.c
```
int main(){
    int a = 1;
    int p = &a;
    return 0;
}
```
The reason why "int p" is to first fix the UnaryOperator::Address problem first.

My IR result: 
```
fun i32 @main () {
init:
  bid: b0
  allocations:
    %l0:i32:a
    %l1:i32*:p

block b0:
  %b0:i0:unit = store 1:i32 %l0:i32*
  %b0:i1:i32 = load %l0:i32*
  %b0:i2:i32 = typecast %b0:i1:i32* to i32 <--- diff
  %b0:i3:unit = store %b0:i2:i32 %l1:i32*
  ret 0:i32

block b1:
  ret 0:i32
}
```
IR Solution result:
```
fun i32 @main () {
init:
  bid: b0
  allocations: 
    %l0:i32:a
    %l1:i32:p

block b0:
  %b0:i0:unit = store 1:i32 %l0:i32*
  %b0:i1:i32 = load %l0:i32*
  %b0:i2:i32 = typecast %l0:i32* to i32 <--- diff
  %b0:i3:unit = store %b0:i2:i32 %l1:i32*
  ret 0:i32

block b1:
  ret 0:i32
}
```

So i'm really trying to get `%l0:i32*` instead of `%b0:i1:i32*`.
What I did on UnaryOperator::Address(on translate_unary_op):
1. translate_expr_rvalue(&op.operand.node) -> op.operand is "a"
2. On translate_expr_rvalue, we get a's address by Expression::Identifier(), and get new operand.
3. With new operand, make new register which has same register id with new operand, but make dtype as `ir::Dtype::Pointer { inner: Box::new(dtype), is_const: false }`. This is because we have to get &a's value. But it fails with "%b0:i1:i32*". 

Q1.
I thought that if i just return ptr value on translate_expr_rvalue, i could achieve the purpose but then load instruction will be disappeared. What could i do more to solve this problem?

By the way, while writing this question, I found that if i use
let operand = translate_expr_rvalue(operand)
let operand = translate_expr_lvalue(operand)
make new register with same register id + make dtype as pointer, then my IR changes to this(Only block b0):
```
block b0:
  %b0:i0:unit = store 1:i32 %l0:i32*
  %b0:i1:i32 = load %l0:i32*
  %b0:i2:i32 = typecast %l0:i32** to i32 -> we have to get '%l0:i32*'
  %b0:i3:unit = store %b0:i2:i32 %l1:i32*
  ret 0:i32
```
I couldn't understand why mixing rvalue + lvalue could solve this problem. Is there any some kind of explanation? 

Q2.
This looks similar with ir solution, but slightly different. is there any possible code block that make one more *?

Q3.
Also i have one more question. Do i need to make somehow method to distinct translate_expr_rvalue vs translate_expr_lvalue on UnaryOperator::Address?(on translate_unary_op)
What i'm thinking is that, if we are calculating the left side value, then i think i have to use translate_expr_lvalue function instead of translate_expr_rvalue.
(if c code is int *p = &a, then for *p, i use translate_expr_lvalue and for &a, use translate_expr_rvalue)
Is this true?

---------------------------------------
kst 5/18 am 1:30 fixed. sorry

**Comment by minseongg** [comment]
### Q1

For the translation of unary expression with address operator (e.g. `&a`), you need to return the pointer value which points to the operand. Since this value can be obtained by `translate_expr_lvalue`, you could solve the problem by using it. Actually, the instruction `%b0:i1:i32 = load %l0:i32*` in the solution IR is needless, you could ignore it.

### Q2

It seems like you are adding additional * to the result of `translate_expr_lvalue`, I recommend you to check it.

### Q3

Since the only possible operator for the unary expression as lvalue is `UnaryOperator::Indirection`, we translate unary expression in lhs in the `translate_expr_lvalue`. (https://youtu.be/jFahkyxm994?t=1813) Therefore, you could consider that `translate_unary_op` translates unary expression in rhs. (Translation of `*p` is done in `translate_expr_lvalue`.)

If there is something I misunderstood your question, feel free to ask more questions.

**Comment by junsooo** [comment]
Thank you very much for your detailed explanation. i solved the problem.
