### ISSUE TITLE
[HW3] How to make two loops(w/o multiple borrow occurs) in SimplifyCfgMerge

### ISSUE THREAD

**Issue by junsooo** [kaist-cp/cs420#416]
Hello, now i'm doing HW3.

As #129, I wanted to make two loops to solve the problem.
First one is saving infos, and the second one is actual removing or replacing.. etc.

I made first loop with this:
```
// some variables i.e 
// let mut block_froms: Vec<&Block> = Vec::new();
// let mut block_tos: Vec<&Block> = Vec::new();
// let mut arg_bids: Vec<&BlockId> = Vec::new();
// let mut replaces: HashMap<RegisterId, Operand> = HashMap::new();

for (bid_from, block_from) in &code.blocks {
    if let BlockExit::Jump { arg } = &block_from.exit {
            if *bid_from != arg.bid && indegrees.get(&arg.bid) == Some(&1) {
                  ...
    }
}
```

And on second loop:
```
let mut index = 0;
for arg_bid in arg_bids {
            let block_to = code.blocks.remove(arg_bid).unwrap();
            ...
}
```
But on `let block_to = code.blocks.remove(arg_bid).unwrap();` line,
"Cannot borrow `code.blocks` as mutable because it is also borrowed as immutable" error and "multiple borrow occurs here" happens.

I'm really curious why this happen cause first loop is already ended, so that borrowed range should be finished. But error happens.
If this is because of some new variables i introduce like block_froms, or block_tos .... then how can i save and mark the variable to erase or fix on second loop?

**Comment by minseongg** [comment]
It seems like the error occurs because `code.blocks` is immutably borrowed by the elements of `arg_bids` and since the elements of `arg_bids` are used in the second loop, so the borrowed range of `code.blocks` is not finished after the first loop. (Similarly, [this code](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=9235bb71c2c3fc6ec013cd78fcb2f7a2) fails to compilation)

You could solve it by using `Vec<BlockId>` instead of `Vec<&BlockId>` for `arg_bids`.

**Comment by junsooo** [comment]
Thank you very much. It was very helpful.
