### ISSUE TITLE
[Homework 7] Storing to global variable

### ISSUE THREAD

**Issue by andersc97** [kaist-cp/cs420#419]
When you're asking a question, please make sure:

- [ ] You clarify your questions as clear as possible.  If possible, please make it a yes/no question.  If possible, please summarize your question in one sentence at the beginning of an issue.

- If you're asking a question on concepts:
    + [ ] You read the corresponding sections of the slide.
    + [ ] You searched for the concepts using search engines and Wikipedia.

- If you're asking a question on Rust programming:
    + [ ] You searched for error messages or any relevant logs using search engines.
    + [ ] Your problem is reproducible in the provided server.  Please describe how others can reproduce your problem.
    + [ ] You paste code, if any, in text with [syntax hightlight](https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks).  No images.
    + [ ] You paste code, if any, that is minimized as much as possible.  Your code should be immediately relevant to your question.

--

While trying to understand how RISC-V handles global variables, I tried executing godbolt's example assembly code using qemu.  However, it results in segmentation fault.  I was wondering what is wrong with godbolt's implementation:
![image](https://user-images.githubusercontent.com/20104363/170845568-2c6b1e41-70b0-481b-a27f-5f8206920d16.png)
Specifically, I suspect that it is the lui/sb instructions which cause segfault while trying to store to the global variable 'temp'.  I wasn't able to find any detailed explanation on how to save to global variable, so I don't know the reason why godbolt's code isn't working.

**Comment by minseongg** [comment]
The segmentation fault occurs at `sb` instruction because the 'temp' variable is declared in the `.text` section, which is allocated in a read-only memory section. (https://stackoverflow.com/questions/55107587/what-are-assembler-section-directives-used-for) It can be resolved by adding directives to the 'temp' variable like this:

```assembly
	.globl main
	.section	.data
temp:
        .zero   1
	.section	.text
main:
        addi    sp,sp,-16
        sd      s0,8(sp)
        addi    s0,sp,16
        lui     a5,%hi(temp)
        li      a4,54
        sb      a4,%lo(temp)(a5)
        li      a5,1
        mv      a0,a5
        ld      s0,8(sp)
        addi    sp,sp,16
        jr      ra
```

It seems like directives are omitted in the godbolt's output because it was filtered out. If you uncheck `Directives` option in the filter menu at the top of the compiler window, you'll find section directives. Please try it.
