### ISSUE TITLE
Will you upload updated /src/irgen/mod.rs? 

### ISSUE THREAD

**Issue by kimjungwow** [kaist-cp/cs420#42]
In [IRgen video](https://www.youtube.com/watch?v=HjARCUoK08s&feature=youtu.be), **/src/irgen/mod.rs** code (in video) is quite different from what was uploaded 13 days ago.  

Homework 2 is implementing IRGen in this file, and I wonder whether updated **src/irgen/mod.rs** will be uploaded.   

It's because there are some boilerplate codes such as `impl Translate<Parse> for Irgen`. I wonder whether I can directly use those boilerplate codes.  

Moreover, `impl fmt::Display for IrgenError` is different in uploaded file and file in video.  In uploaded file, it uses `write!(f, "IrgenError")`, but there is `write!(f, "error: {}\r\n\r\ncode: {}", self.message, self.code)` in video.  

If updated file will be uploaded, it will be helpful to get it before we do too much homework2!  
Thanks in advance!

**Comment by cmpark0126** [comment]
Thank you for your question. However, since the part you pointed out is a code that does not affect the IR test we designed, there will be no problem solving the homework.

FYI, we are using customed `IrgenError` struct to get an informative error message when compile error occurs. Likewise, You can customize and use `IrgenError` the way you want.

**Comment by jeehoonkang** [comment]
The code shown in the video is actually a part of the model solution.  We expect you to implement on your own :)

**Comment by kimjungwow** [comment]
Thank you!!
