### ISSUE TITLE
[HW4] When should end_values' temp reg operand changed to phinode?

### ISSUE THREAD

**Issue by junsooo** [kaist-cp/cs420#428]
Sorry for some kinds of repeated questions in hw4.

---------------------------
Hello, now i'm doing HW4.

On ir1/simple_cond.ir, there is block b3.
```
block b3:
  %b3:i0:i32 = load %l2:i32*
  %b3:i1:unit = store %b3:i0:i32 %l1:i32*
  %b3:i2:i32 = load %l0:i32*
  %b3:i3:i32 = load %l1:i32*
  %b3:i4:u1 = cmp lt %b3:i2:i32 %b3:i3:i32
  br %b3:i4:u1, b4(), b5()
```
And the model solution is:
```
block b3:
  %b3:p0:i32:t0
  %b3:i0:unit = nop
  %b3:i1:unit = nop
  %b3:i2:unit = nop
  %b3:i3:unit = nop
  %b3:i4:u1 = cmp lt %b0:i2:i32 %b3:p0:i32 --------------> But my implementation: %b3:i0:i32
  br %b3:i4:u1, b4(), b5()
```
So, my implementation is wrong, and i thought about the reason.
 - %b3:i3:i32 is loaded value of %l1:i32*
 - And that value is %b3:i0:i32 which is loaded value of %l2:i32*
 - So on Instruction::Store part(`for (bid, block) in &code.blocks`), end_value for ( (aid: 1, BlockId(3)), `Temp register (BlockId(3), iid: 0))` is inserted.

Because of the inserted `Temp register (BlockId(3), iid: 0))`, my ir prints %b3:i0:i32 instead of %b3:p0:i32.
To solve this problem, i think this end_value should be changed with related phinode. 
In this example, `Temp register (BlockId(3), iid: 0))` should be changed into `Arg register (BlockId(3), aid: 0)`.
I tried hard but couldn't find the location which part should i put that logic.
I think end_value should be fixed after phinode is inserted, so the candidate is `//Generates phinodes recursively` part. But the current logic is about #183's 4-line algorithm + phinode_visited.insert or phinode_stack.push, so now i'm confused.

What am i misunderstanding? Thank you very much.

**Comment by minseongg** [comment]
One way to solve it is using `replaces` before adding end value when you meet `store` instruction so that the end values will not point to the `nop` after the removal of store/load instructions.

For `simple_cond` example: (considered instructions in the block which is related to `%l1`)

- `%b3:i0:i32 = load %l2:i32*`

  `b3` is a join point, insert a phinode and it'll be the load result.

  + end_values: `{%l2 |-> %b3:p0}`
  + replaces: `{%b3:i0 |-> %b3:p0}`

- `%b3:i1:unit = store %b3:i0:i32 %l1:i32*`
  
  Since `%b3:i0 |-> %b3:p0` is in the replaces, the end value of `%l1` is **updated to `%b3:p0` instead of `%b3:i0`**. 

  + end_values: `{%l2 |-> %b3:p0, %l1 |-> %b3:p0}`
  + replaces: `{%b3:i0 |-> %b3:p0}`

- `%b3:i3:i32 = load %l1:i32*`

  The end value of `%l1` is `%b3:p0`, add `%b3:i3 |-> %b3:p0` to replaces.

  + end_values: `{%l2 |-> %b3:p0, %l1 |-> %b3:p0}`
  + replaces: `{%b3:i0 |-> %b3:p0, %b3:i3 |-> %b3:p0}`

**Comment by junsooo** [comment]
Thank you for your big help. It was very helpful.
