### ISSUE TITLE
[HW5] About GVN algorithm's details

### ISSUE THREAD

**Issue by junsooo** [kaist-cp/cs420#430]
Hello, now i'm doing HW5.

I have some questions about implementation details for HW5.
This video(https://www.youtube.com/watch?v=ICxRjSz7AtU&list=PL5aMzERQ_OZ8RWqn-XiZLXm1IJuaQbXp0&index=26 28:26) says that
Expression table (ET): Expr<Num> -> Num   e.g circle(2) + 37 -> circle(3), and input type is Expr<Num>.

Q1. Is 37 a num? I think it is constant operand, so i think it is not num.

Q2. Actually I couldn't understand why input type is Expr<Num>. For example, Is it (Operand, lhs, rhs) for Binop instruction?(circle(2), Operator::Plus, Operand::Constant(37)). Then input type can be (usize, BinaryOperator, operand).. What am i misunderstanding?

Q3. Do i have to update the operand table when lhs or rhs is constant? I think answer is no, but after i watch https://github.com/kaist-cp/cs420/issues/407, i'm confused. Maybe that issue's constant could be only for jump instruction. Is that right?

Q4. Followup question for Q2. I think i should consider all kinds of instruction, for example Unary instruction. Unary Instruction's operand type is different with binary operation, so I think i have to make expression table(ET)'s input type using some kinds of multiple types. Is it correct? (example: it should accept BinaryOperator::Plus, UnaryOperator::Negate)

Q5. 
This is from GVN lecture,
![image](https://user-images.githubusercontent.com/22411406/171350917-5e61e5ec-a578-46e8-862d-6666ce7b0847.png)
I have question for 
circle(1) + 37: circle(2),
%x1: circle(2) line.
So, if i put "circle(1) + 37" line to expression table and get Num(2), do i have to insert %x1 in expression table also? I couldn't understand that, for next instruction(%y1 = %x1 + 42) i watch %x1 but this %x1 is just register, not (circle(1), +, 37) so can not recognize it. 
I think i can solve this problem with counting current instruction index(iid) and make temp register with iid and put that info in register table. But in this case, I shouldn't get new number for table because (circle(1), +, 37)'s number and %x1's number should be same as Num(2). Is it correct?

Thank you for your answer.

**Comment by Lee-Janggun** [comment]
#Q3
- Yes, you should update the register table. This is the situation mentioned in slide number 75: "Example 3: global value numbering with phinodes".
- In the figure , you need to note that the two registers `b1:i0` and `b2:i0` are syntactically the same.
- Thus, you can deduce that we can insert a phi-node in `b3`, because the same computation of `42 + 37` will be done no matter if the control flows from `b0 -> b1 -> b3` or `b0 -> b2 -> b3`.


# Q2
> Then, should i make some kind of enum of expr(accepts Operand, BinOp, UnaryOp, Dtype..) and make Vec of expr, and implement manually checking that vector's equality?

- Yes, that is what I did. Actually in HW4, something similar was done already: we had the enum `OperandVar`, to denote that we can replace with new phinodes that did not exist in the code beforehand.
> Should i put dtype on Vec of expr? (circle(1) + 37) with i32 something like that. I think yes..
- First off, I recommend using a HashMap then a Vec, since the expression table is `Expr<Num> -> Num`. Rust has very nice #[derive] macros that you can place on top of enum/struct definitions to make them automatically hashable.
- You actually must. For instance, `1 + 2` have different semantics when the types of operands, and the resulting dtype are different. Remember https://github.com/kaist-cp/cs420/issues/106 :)
> There's a args:Vec on Call Instruction, so for call instruction, do i have to make logic for checking (callee, args, return_type) is same? which means all arguments should be same to get same circle(num)
- Actually consider this: Does GVN for *function calls* make sense? Are you sure you can replace the result of a later function call with an earlier one just because one dominates the other?


# Q5
> %a + 37 is first instruction of block, so iid is 0. So make temp register with this blockId and iid 0, put that temp register in RT with circle(2). So on next instruction(%y1 = %x1 + 42), I have to check first that %x1 is already in RT. Is this correct?
- This worked for me. I think one of the reasons that in IR, register are named simply by their instruction number is to make these kinds of simplifications possible.
