### ISSUE TITLE
[Lecture] New ModRef API

### ISSUE THREAD

**Issue by andersc97** [kaist-cp/cs420#443]
When you're asking a question, please make sure:

- [ ] You clarify your questions as clear as possible.  If possible, please make it a yes/no question.  If possible, please summarize your question in one sentence at the beginning of an issue.

- If you're asking a question on concepts:
    + [ ] You read the corresponding sections of the slide.
    + [ ] You searched for the concepts using search engines and Wikipedia.

- If you're asking a question on Rust programming:
    + [ ] You searched for error messages or any relevant logs using search engines.
    + [ ] Your problem is reproducible in the provided server.  Please describe how others can reproduce your problem.
    + [ ] You paste code, if any, in text with [syntax hightlight](https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks).  No images.
    + [ ] You paste code, if any, that is minimized as much as possible.  Your code should be immediately relevant to your question.

--

I was reviewing the lecture video regarding AA and ModRef analysis, and I still don't understand one thing about the design about the new ModRef API.  Why does the additional information only contain MustAlias?  Are PartialAlias and MayAlias information unnecessary during LLVM compilation?

**Comment by jeehoonkang** [comment]
I think it's a design choice: MustAlias information unleashes a lot of optimization opportunities, and it's cost-effective to add such information to ModRef analysis. We can theoretically add other alias results to ModRef as well, but its return is significantly smaller, e.g., we cannot skip stores using a walker with only MayAlias result.

**Comment by Lee-Janggun** [comment]
I think we can find insight on what the speaker mentioned last on why there is no `MustNoModRef`.
- Even though this enum variant exists, it is not exposed.
- This is because they do not think that the combination of `MustAlias` and `NoModRef` have additional benefit then that of `NoModRef`. Hence, they do not expose it.
- Also, they mentioned that doing AA was expensive, so we want the one AA analysis session we do to be most efficient, which was only adding `MustAlias` info to `ModRef` info, I think.
