### ISSUE TITLE
[HW7] About SSA register allocation

### ISSUE THREAD

**Issue by YoonseokJeong** [kaist-cp/cs420#528]
It seems somewhat late to ask a question like this, but application toward actual implementation is quite confusing.

Below is my summarization of the intuition of SSA register allocation.

1. Order matters when coloring the IR registers.
2. PEO yields the optimal coloring order.
3. We can obtain PEO by traversing domination tree in post-order thanks to SSA property.
4. Thus, we can color the IG(interference graph) without constructing  IG itself.

Here, domination relation is the relationship between 'blocks' while interference is the relationship between 'registers'.
I understand that the interference of two registers implies the dominance between their blocks, but I don't think the reverse also holds.
(Domination of A over B doesn't imply registers at A and B interfere.)

So I don't understand how only the "PEO of blocks(not registers)" can give the optimal coloring of registers without comparing the live range of registers and actually constructing IG.

**Comment by jirheee** [comment]
* The domination relation the SSA register algorithm is talking about is domination between **labels**(same definition with what we used in the final exam), not blocks. 

As you mentioned, our domination tree was constructed from the domination relation among blocks. But here, since we need the domination order between registers, you need to either construct domtree of labels from domtree of blocks we currently have or by yourself in a similar way you did for constructing the block dom tree.

**Comment by jirheee** [comment]
Actually, you can recursively walk through the block dominance tree in pre-order and color the registers(Sebastian Hack's Ph.D. thesis algorithm 4.2 in section 4.3). 

Also, if you plan to implement the SSA register allocation from the lecture, I recommend reading section 4 of the thesis.

**Comment by jirheee** [comment]
"We can color the IG(interference graph) without constructing IG itself." means you can allocate the register without materialization of IG(IG as a data structure), but you will have to do some analysis such as if some variable is used last or not.

**Comment by YoonseokJeong** [comment]
Thank you for answering!
