### ISSUE TITLE
[Question] Another possible correct optimization result for complete_cond.ir.

### ISSUE THREAD

**Issue by hercule-karuha** [kaist-cp/cs420#534]
Hello, I have completed HW6 and am currently conducting the test_examples_optimize testing. I have passed all examples except for complete_cond.ir.  But I think that my optimization results are also correct.

This is the func_10 in examples/opt/complete_cond.ir.
```
fun i32 @func_10 () {
init:
  bid: b0
  allocations: 


block b0:
  %b0:i0:u1 = cmp ne 0:i32 0:i32
  br %b0:i0:u1, b4(), b5()

block b2:
  %b2:i0:u1 = cmp ne 1:i32 0:i32
  br %b2:i0:u1, b33(1:i32), b33(0:i32)

block b3:
  %b3:p0:i32:t12
  %b3:i0:u1 = cmp eq %b3:p0:i32 0:i32
  %b3:i1:i32 = typecast %b3:i0:u1 to i32
  ret %b3:i1:i32

block b4:
  br %b0:i0:u1, b3(1:i32), b2()

block b5:
  br %b0:i0:u1, b3(1:i32), b2()

block b30:
  %b30:p0:i32:t11
  j b3(%b30:p0:i32)

block b33:
  %b33:p0:i32:t8
  %b33:i0:u1 = cmp ne %b33:p0:i32 0:i32
  br %b33:i0:u1, b30(0:i32), b30(1:i32)
}
```

This is my output.
```
fun i32 @func_10 () {
init:
  bid: b0
  allocations: 


block b0:
  %b0:i0:u1 = cmp ne 0:i32 0:i32
  br %b0:i0:u1, b3(1:i32), b2()

block b2:
  %b2:i0:u1 = cmp ne 1:i32 0:i32
  br %b2:i0:u1, b33(1:i32), b33(0:i32)

block b3:
  %b3:p0:i32:t12
  %b3:i0:u1 = cmp eq %b3:p0:i32 0:i32
  %b3:i1:i32 = typecast %b3:i0:u1 to i32
  ret %b3:i1:i32

block b30:
  %b30:p0:i32:t11
  j b3(%b30:p0:i32)

block b33:
  %b33:p0:i32:t8
  %b33:i0:u1 = cmp ne %b33:p0:i32 0:i32
  br %b33:i0:u1, b30(0:i32), b30(1:i32)
}

```
I tried to analyze the CFG of ir4/complete_cond.ir. Here is a partial screenshot of it.
I believe that in the optimized result, we can eliminate block 4 and block 5.

![image](https://github.com/kaist-cp/cs420/assets/89474649/bb185976-dbc7-454c-82fe-b78ead8c6777)

Using simplify cfg and dead code elimination, blocks 4 and 5 can be removed. However, they are retained in opt/complete_cond.ir.

I would like to confirm whether my output results are also correct.
I am not a student of KAIST. Thank you for offering such an excellent course publicly; it has truly contributed significantly to my learning and development.

**Comment by travis1829** [comment]
I think your optimization itself makes sense. However, it seems that we only need to do simple optimizations during simplify_cfg, and hence, such optimization doesn't happen in the reference solution.

I'm not sure how you implemented simplify_cfg, but if we compare `examples/opt/complete_cond.ir` and your output, it seems that you changed block `b0`'s block exit from `br %b0:i0:u1, b4(), b5()` to `br %b0:i0:u1, b3(1:i32), b2()` (which is the block exit of `b4` and `b5`) based on the fact that block `b4` and `b5` are empty and their block exits are identical.

However, according to what I know, we optimize a `BlockExit::ConditionalJump { condition, arg_then, arg_else }` only for the following simple case.
* `arg_then == arg_else` (**SimplifyCfgConstProp**)
* `condition` is constant 0 or constant 1. (**SimplifyCfgConstProp**)
* `arg_then` is an empty block and its block exit is a simple jump. (**SimplifyCfgEmpty**)
* `arg_else` is an empty block and its block exit is a simple jump. (**SimplifyCfgEmpty**)

Because `b0`'s block exit is not one of these case, we can't optimize it anymore. This becomes clear if you watch https://youtu.be/d_Op82Npn5Y?si=VMuLLRl4KOHo0zIl&t=933 (at 15:33) and https://youtu.be/d_Op82Npn5Y?si=EGu1C-WD7nUcPvSn&t=943 (at 15:43), which includes hints for the reference solution. I think this was also mentioned in class, but unfortunately, seems like such hints aren't mentioned in this repo so you couldn't know about it.

**Comment by hercule-karuha** [comment]
After deadcode eliminate, `b4` to `b15` (The portion marked with a blue line in the picture)  will all become empty. 
Because the block exit condition for `b9`, `b4`, `b5`, `b6` have been replaced with `b0:i0` by gvn , their own phinodes and instructions have become deadcode.
`b0`'s block exit is `br %b0:i0:u1, b7(), b8()` can be optimize to `br %b0:i0:u1, b9(), b9()` . So the `arg_then == arg_else` .
The same thing will happen for `b4` and `b5` ; both can directly jump to `b6` .
As a result, `b0` can jump directly to `b6`.
I want to know if I make some mistakes.

**Comment by travis1829** [comment]
Actually..., I think you don't need to care about this issue.
I've just noticed that `test_examples_optimize` is not used in any homework grading script, so it's just some dead code that the TA maybe forgot to remove. (Maybe they initially planned to use it for grading but decided not to because stuff like this could happen?) Note that after HW7 (asm gen), your output doesn't need to be the same with the reference solution anymore.

Additionally, your optimization itself seems correct (or maybe even better than the reference solution in terms of the final project (performance competition)). I think subtle changes between your solution and the reference solution caused this issue, which isn't really important according to what I think.

**Comment by hercule-karuha** [comment]
Thank you very much. I brought up this issue just because I wasn't sure if I was correct, so I raised it to confirm. Now that I have no question, I've closed this issue.

**Comment by Lee-Janggun** [comment]
`test_examples_optimize` is a just a reference to use for students that wishes to do HW7 and beyond. Some optimization bugs can only be seen when two or more of them are used at the same time in multiple iterations, and this function does that.
