### ISSUE TITLE
[HW2] Multiple Typedef Declaration & Cargo Run -i Output Explanation

### ISSUE THREAD

**Issue by Ngiong** [kaist-cp/cs420#54]
Hello,

I tried to test my irgen implementation using `cargo run --bin kecc -- -i examples/fibonacci.c` for typedef corner case (multiple typedef declaration with the same type)

```c
// examples/fibonacci.c
typedef int ii;
typedef int ii;

ii x = 5;

int fibonacci(ii n) {
    if (n < 2) {
        return n;
    }

    return fibonacci(n - 2) + fibonacci(n - 1);
}

int main() {
    return fibonacci(9) == 34;
}

```
However, the 2nd declaration of `typedef int ii;` gives
`DtypeError("typedef' cannot be used with scalar type or signed option")`

In my implementation, I tried to use the `try_from_ast_declaration_specifiers` function 
for every `ast::Declaration` found.
```rust
fn translate(&mut self, source: &ast::Declaration) -> Result<Self::Target, Self::Error> {
        // specifier
        let (dtype, is_typedef) =
            Dtype::try_from_ast_declaration_specifiers(&source.specifiers)
                .map_err(|e| IrgenError::DtypeError(e))?;
...
```

Is there any precondition for that function that I possibly missed out?
Thank you.

--
2nd Question.
By the way, can you also explain what is the expected output of running `cargo run --bin kecc -- -i examples/fibonacci.c` ? So far, I only get this kind of output.
```
<variable list>

x = 5 i32


<function list>

declare i32 @main()

declare i32 @fibonacci(i32)


Process finished with exit code 0
```
--

Thank you.

**Comment by Ngiong** [comment]
Update for my 2nd question: 

After re-watching the video,
and adding the `ir::FunctionDefinition` to the `ir::Declaration` struct
now running the `cargo run --bin kecc -- -i examples/fibonacci.c` gives more output
(so happy :heart_eyes: :heart_eyes:)
 
```
define i32 @fibonacci(i32) {
init:
  bid: b0
  allocations: 
    %l0:i32:n

}

define i32 @main() {
init:
  bid: b0
  allocations: 


}
```
Now I am not sure about the same bid **b0** in `@fibonacci` and `@main`,
shouldn't it be **b0** and **b1** ?
(I thought when the main function calls the Fibonacci function, it jumps from **b0** to **b1**?, cmiiw)

Since the HW2 IRgen is pretty huge,
Perhaps, can I get a tip on how can I verify the correctness of my implementation
during the _work-in-progress_ development stage?

Thank you so much :satisfied:

**Comment by cmpark0126** [comment]
Thank you for the question :)

1st, multiple typedef declaration bug is derived from `lang_c` library bug, so that we cannot fix it directly. By the way, we don't have any plan to test whether multiple typedef declaration is allowed or not, so you don't need to worry about this case.

(FYI, we will report this bug you pointed out to the `lang_c` library soon.)

2nd, `BlockId` (i.e., `b0`, `b1`) is a kind of local element of the function. So, when the `main` function calls the `fibonacci` function, `PC`(program counter) jumps to `b0` of the `fibonacci` function. Please refer this code: [ir/interp.rs#L1116-L1118](https://github.com/kaist-cp/kecc-public/blob/72ec63ea82509b3e15ee023def875efb65b0b11c/src/ir/interp.rs#L1116-L1118)

**Comment by cmpark0126** [comment]
The `IR` below is an example of compiling `examples/fibonacci.c` with `kecc` :
```llvm
<variable list>



<function list>

define i32 @main() {
init:
  bid: b0
  allocations: 


block b0
  %b0:i0:i32 = call %fibonacci(9:i32)
  %b0:i1:u1 = cmp eq %b0:i0:i32 34:i32
  %b0:i2:i32 = typecast %b0:i1:u1 to i32
  ret %b0:i2:i32

block b1
  ret 0:i32

}

define i32 @fibonacci(i32) {
init:
  bid: b0
  allocations: 
    %l0:i32:n

block b0
  %b0:i0:unit = store %b0:p0:i32 %l0:i32*
  %b0:i1:i32 = load %l0:i32*
  %b0:i2:u1 = cmp lt %b0:i1:i32 2:i32
  br %b0:i2:u1, b1([]), b2([])

block b2
  j b3([])

block b1
  %b1:i0:i32 = load %l0:i32*
  ret %b1:i0:i32

block b4
  j b3([])

block b5
  ret undef:i32

block b3
  %b3:i0:i32 = load %l0:i32*
  %b3:i1:i32 = sub %b3:i0:i32 2:i32
  %b3:i2:i32 = call %fibonacci(%b3:i1:i32)
  %b3:i3:i32 = load %l0:i32*
  %b3:i4:i32 = sub %b3:i3:i32 1:i32
  %b3:i5:i32 = call %fibonacci(%b3:i4:i32)
  %b3:i6:i32 = add %b3:i2:i32 %b3:i5:i32
  ret %b3:i6:i32

}
```

Also, you can get a similar form of `IR` when using `llvm`. Please use https://godbolt.org/ actively ;)

**Comment by cmpark0126** [comment]
> Since the HW2 IRgen is pretty huge,
Perhaps, can I get a tip on how can I verify the correctness of my implementation
during the work-in-progress development stage?

Great question! 

First, I recommend you need to split the whole problem into small chunks based on the example codes we provided. 

Second, when solving the problem, please refer to the `llvm`'s IR. Because `kecc`'s IR is inspired by `llvm`'s IR, It can be a role model of correctness.

Third, If you cannot figure out, feel free to create an issue. we will do our best to answer as soon as possible, and we encourage students to answer each others’ questions. :)

**Comment by Ngiong** [comment]
Thank you for the reply @cmpark0126 
It's very helpful ^^
