### ISSUE TITLE
C-Reduce cannot run because the interestingness test does not return zero.

### ISSUE THREAD

**Issue by Pusnow** [kaist-cp/cs420#55]
When I try to reduce a fuzzed source, I've got below error.
I've already passed many fuzz test cases.

```bash
$ python3 tests/fuzz.py --print --reduce  -n1   
Building KECC..
    Finished release [optimized] target(s) in 0.10s

C-Reduce cannot run because the interestingness test does not return
zero. Please ensure that it does so not only in the directory where
you are invoking C-Reduce, but also in an arbitrary temporary
directory containing only the files that are being reduced. In other
words, running these commands:

  DIR=`mktemp -d`
  cp /home/pusnow/dev/kecc/tests/test_reduced.c $DIR
  cd $DIR
  /home/pusnow/dev/kecc/tests/reduce-criteria.sh
  echo $?

should result in "0" being echoed to the terminal.

See "creduce --help" for more information.


Traceback (most recent call last):
  File "tests/fuzz.py", line 274, in <module>
    creduce(tests_dir, fuzz_arg)
  File "tests/fuzz.py", line 208, in creduce
    raise Exception("Reducing test_reduced.c by `{}` failed with exit code {}.".format(" ".join(args), proc.returncode))
Exception: Reducing test_reduced.c by `creduce --tidy ./reduce-criteria.sh test_reduced.c` failed with exit code 1.
```

and the commands retrun `1`.

rustc: rustc 1.42.0 (b8cedc004 2020-03-09)
creduce: creduce 2.9.0 (unknown)
python: Python 3.7.3
gcc: 8.3.0
OS: Debian 10

[test_reduced.zip](https://github.com/kaist-cp/cs420/files/4467921/test_reduced.zip)

**Comment by KunJeong** [comment]
I encountered the same problem. In my case, re-running the fuzzer with `python3 tests/fuzz.py --print`(without reduce) and then reducing solved the problem.
I think merging from master overwrites our test_polished.c, so we need to regenerate the buggy test case before reducing the test with creduce.

**Comment by cmpark0126** [comment]
Thank you for the reporting. we'll check this issue ASAP :)

**Comment by cmpark0126** [comment]
@Pusnow 
Sorry for the late reply. I check this issue.

As @KunJeong 's reply, when you encounter this message you mentioned above, you need to re-run the `fuzzer` without `--reduce`. Because `reduce` works only with buggy test case. 

Please refer to the following steps:

1st. run `python3 tests/fuzz.py --print` (unlimited loop)
- If your `write_c.rs` has a bug, `fuzzer` will find a buggy test case. (after then `fuzzer` is terminated automatically)

2nd. run `python3 tests/fuzz.py --print --reduce`
- At `1st` step, we already find a buggy test case(test_polished.c). The `creduce` try to reduce this test case(not make a new one). 
- Note that if the test case which is `creduce` try to reduced has no bug, error occurs which you mentioned above.

By the way, If you already passed many fuzz test cases, there is no problem I think. :)

**Comment by Pusnow** [comment]
> * Note that if the test case which is `creduce` try to reduced has no bug, error occurs which you mentioned above.

It seems this is my case. Thank you.
