### ISSUE TITLE
[Homework 2] If you have a problem to understand `GetElementPtr` Instruction, please refer to this issue

### ISSUE THREAD

**Issue by jaehyun1ee** [kaist-cp/cs420#78]
I am currently working on handling arrays in the irgen. While testing my irgen with some simple C codes, I found out that my irgen gives different results for similar codes and I want to ask for help in debugging.

Specifically, I executed the below command,

```
cargo run --release --bin fuzz -- -i /home/s20180491/kecc-public/tests/test_reduced.c
```

where tests/test_reduced.c is a sample code that I wrote.

The results were different as follows.

1. 
For the below C code,  

```c
int main() {
    int a[10];
    for(int i = 0; i < 10; i++) {
        a[i] = i;
    }
    return a[5] == 5;
}
```

the result is,

```
gcc: 1, kecc: 0
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`', src/tests.rs:91:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

2. 
However, if I give a similar C code as below,

```c
int main() {
    int a[10];
    for(int i = 0; i < 10; i++) {
        a[i] = i;
    }
    return a[5];
}
```

the result is

```
gcc: 5, kecc: 5
```
 
 <br/>

The codes in 1 and 2 differs only in the return statements and given the result of 2, I think 1 should pass without any problem. (I also checked that the binary operator == works fine for many cases including 5 == 5).

I thought of several reasons why this happened. I guess while typecasting the result of == to type u1, some error happened or I may be translating the index operator in a wrong way. I tried to debug it for a long time, but I cannot come up with a clear solution. May I ask for some help or tip in debugging?

And Below is the result of my irgen for C code in example 1.

```
<variable list>



<function list>

define i32 @main() {
init:
  bid: b0
  allocations: 
    %l0:[10 x i32]:a
    %l1:i32:i

block b1
  %b1:i0:unit = store 0:i32 %l1:i32*
  j b2([])

block b6
  ret 0:i32

block b2
  %b2:i0:i32 = load %l1:i32*
  %b2:i1:u1 = cmp lt %b2:i0:i32 10:i32
  br %b2:i1:u1, b4([]), b5([])

block b0
  j b1([])

block b3
  %b3:i0:i32 = load %l1:i32*
  %b3:i1:i32 = add %b3:i0:i32 1:i32
  %b3:i2:unit = store %b3:i1:i32 %l1:i32*
  j b2([])

block b4
  %b4:i0:i32* = getelementptr %l0 offset 0
  %b4:i1:i32 = load %l1:i32*
  %b4:i2:i32* = getelementptr %b4:i0 offset %b4:i1
  %b4:i3:i32 = load %l1:i32*
  %b4:i4:unit = store %b4:i3:i32 %b4:i2:i32*
  %b4:i5:i32 = load %b4:i2:i32*
  j b3([])

block b5
  %b5:i0:i32* = getelementptr %l0 offset 0
  %b5:i1:i32* = getelementptr %b5:i0 offset 5
  %b5:i2:i32 = load %b5:i1:i32*
  %b5:i3:u1 = cmp eq %b5:i2:i32 5:i32
  %b5:i4:i32 = typecast %b5:i3:u1 to i32
  ret %b5:i4:i32

}
```

Thank you in advance :-)

**Comment by cmpark0126** [comment]
Thank you for the question! Actually, I found the bug in your IR.
Originally, I wouldn't help you debug, but I'd like to share this case because this case will be very helpful to other students.

Your problem is from misunderstanding about `offset` of [`GetElementPtr`](https://github.com/kaist-cp/kecc-public/blob/7569d5ad83398ee5daf386d852acf6ecab381ba6/src/ir/mod.rs#L215-L221). The `offset` of this instruction means byte address unlike `LLVM IR`. So, when you use `GetElementPtr` instruction, you need to pass `index * 4 byte(size of 'i32')`

FYI, our code is like memory, so your code is work like below.
```c
(1st for loop)
a[10] = [byte][byte][byte][byte][byte][byte][byte][byte] ...
        [0]   [0]   [0]   [0]

(2nd for loop)
a[10] = [0][0][0][0][byte][byte][byte][byte] ...
           [0][0][0][1] // value store nested space.

(after for loop finish)
a[10] = [0][0][0][0][1][2][3][4][5][6][7][8][9][undef] ...

(when you load `a[5]`, the value is obtained below)
a[5] = 0x2345 (hex)
```
Interestingly, when we compare the result between `gcc` and `kecc`, the result value is truncated to `i8`. So, in the `code 2` you mentioned above, the result value `0x2345` transformed to `0x0005` and pass the test. Please refer [`test.rs`](https://github.com/kaist-cp/kecc-public/blob/7569d5ad83398ee5daf386d852acf6ecab381ba6/src/tests.rs#L86-L91).

**Comment by cmpark0126** [comment]
Please leave this issue though you resolve the problem. This issue will be helping other students also. Again, thank you for share this case!

**Comment by wenko99** [comment]
Oh, I see. So I must have been very lucky to get the same results from gcc and kecc for `code 2` 😆

Thank you for your kind help as always!

**Comment by cmpark0126** [comment]
This issue is very helpful to implement homework 2, so I'll keep the issue open. ;)
