### ISSUE TITLE
[Homework 2] Type and typecasting

### ISSUE THREAD

**Issue by umartaufiqul** [kaist-cp/cs420#88]
I think I don't quite grasp the basic of type casting, and I have a really hard time understanding what should be done in typecasting.
1. So what I understand is translate_typecast take an operand, a target type, and context, and then change the operand's type, and return it. Is this correct?
2. Is there any guide regarding how each type cast to another type e.g from Int to Float (do the float take the same width from int)
3. Are there specific combinations of dtype casting that is not allowed? For example, is float to array casting allowed?
4. For merge dtype, is there rule about which dtype should be choosen out of the two?

 Thank you in advance.

**Comment by cmpark0126** [comment]
Thank you for the great question :)

1. Yes, you're right.

2. Good point. Actually, we've designed `typecast` as students can easily use. So, you don't need to consider the `width` or `is_signed` option seriously. However, when you use `target type` which has `is_const` as `true`, you need to convert this `is_const` to `false` before using it.

3. FYI, we only allow the cases: `int -> int`, `int -> float`, `float -> int`, `float -> float`. Please refer to this link: [interp.rs#L626-L689](https://github.com/kaist-cp/kecc-public/blob/61b21624081e78085c6073aa6d2c53d9cfa792df/src/ir/interp.rs#L626-L689)

3. Yes. But, I can't tell you the rules here, because we expect students to find themselves. If you are having trouble finding the rules, please refer to the following link: https://www.guru99.com/c-type-casting.html

**Comment by umartaufiqul** [comment]
Thank you for the comprehensive answer!
